### ISSUE TITLE
DRF-like Browsable API?

### ISSUE THREAD

**Issue by sloria** [sloria/aiohttp_utils#1]
Proposal: Port django-rest-framework's browsable API .

Considerations:
- Is this necessary if aiohttp_debugtoolbar adds the REST API debug panel (https://github.com/aio-libs/aiohttp_debugtoolbar/issues/19)?
- Does this belong in this package? I am considering a separate package, aiohttp_api, which ports the browsable API as well as generic CRUD resource classes.

**Comment by jettify** [comment]
I have similar thoughts for long time, but have not started it myself because:

1) DRF rely on ORM , where a lot of information is available, asyncio does not have proper ORM yet (but will have not in distant future). Otherwise we force user to describe data structure of input/output, I believe browsable api should be semi auto generated and should require minimum user interaction.
2) Browsable API should be part of generic REST framework, witch is other story how to implement

I think  aiohttp_api deserves separate package even if  aiohttp_debugtoolbar will have REST toolbar.

**Comment by sloria** [comment]
Valid points. DRF's browsable API is useful insofar as it can introspect DRF Serializers and can therefore generate forms for POST/PUT/etc. Otherwise, it wouldn't provide much more than a GUI client like Postman. 

I am more inclined to target language/framework-agnostic API specs such as Swagger, from which a UI can be generated. I might add an aiohttp plugin for [apispec](https://github.com/marshmallow-code/apispec) if there's interest.

**Comment by sloria** [comment]
Holding off on this for now.
